### ISSUE TITLE
Save the last IP to save API requests to Routeu53

### ISSUE THREAD

**Issue by prononext** [crazy-max/ddns-route53#1002]
### Description

Sometimes you would like to have a DNS Update every minute, but normally it is not neccesary. 

To avoid making so many API Requests to Route53 it would be nice to have a last_known_ip file somewhere to check if the IP has changed and only update on changes. 

I saw this on https://github.com/sjmayotte/route53-dynamic-dns which I was testing before, but the multi record sets in that repo did not work stable.

**Comment by crazy-max** [comment]
> it would be nice to have a last_known_ip file somewhere to check if the IP has changed and only update on changes.

How can you ensure the IP on route53 is aligned?
