### ISSUE TITLE
Documentation detailing the IP source

### ISSUE THREAD

**Issue by turb0steve** [crazy-max/ddns-route53#1075]
### Description

Hi - love the project!

Documentation needs a single line that clearly describes where the IP address used is sourced from.
Would save having to install to find out it does not work as expected.

**Comment by crazy-max** [comment]
> Documentation needs a single line that clearly describes where the IP address used is sourced from.

IP is retrieved from multiple providers: https://github.com/crazy-max/ddns-route53/blob/85fd8adbe127538112d386b95bcdc77702e868b5/pkg/wanip/client.go#L71-L96

PR welcomed, thanks!

**Comment by apkatsikas** [comment]
https://github.com/crazy-max/ddns-route53/pull/1161 PR opened for this doc update.
