### ISSUE TITLE
TZ setting getting ignored?

### ISSUE THREAD

**Issue by dnv** [crazy-max/ddns-route53#1166]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/ddns-route53/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem

### Description

ddns-route53 container seems to ignore TZ variable

### Expected behaviour

    environment:
      - "TZ=Europe/Helsinki"
      
   expecting that Europe/Helsinki time is used by container and shown in logs

### Actual behaviour

UTC time is used instead (off by 2 hours)

Tue, 16 Jan 2024 20:46:52 UTC INF Starting ddns-route53 version=v2.11.0
Tue, 16 Jan 2024 20:46:52 UTC INF Configuration loaded from 9 environment variables
Tue, 16 Jan 2024 20:46:52 UTC INF Current WAN IPv4: censored
Tue, 16 Jan 2024 20:46:53 UTC INF WAN IPv4 has not changed for my.little.domain. record set
Tue, 16 Jan 2024 20:46:53 UTC WRN No Route53 record set to update. Skipping...
Tue, 16 Jan 2024 20:46:53 UTC INF Cron initialized with schedule */30 * * * *
Tue, 16 Jan 2024 20:46:53 UTC INF Next run in 13 minutes 6 seconds (2024-01-16 21:00:00 +0000 UTC)

### Steps to reproduce

Deploy container as follows:

version: "3.5"

services:
  ddns-route53:
    image: crazymax/ddns-route53:latest
    container_name: ddns-route53
    environment:
      - "TZ=Europe/Helsinki"
      - "SCHEDULE=*/30 * * * *"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
      - "DDNSR53_CREDENTIALS_ACCESSKEYID=censored"
      - "DDNSR53_CREDENTIALS_SECRETACCESSKEY= censored"
      - "DDNSR53_ROUTE53_HOSTEDZONEID= censored"
      - "DDNSR53_ROUTE53_RECORDSSET_0_NAME=censored."
      - "DDNSR53_ROUTE53_RECORDSSET_0_TYPE=A"
      - "DDNSR53_ROUTE53_RECORDSSET_0_TTL=600"
      - "DDNSR53_ROUTE53_RECORDSSET_1_NAME= censored."
      - "DDNSR53_ROUTE53_RECORDSSET_1_TYPE=A"
      - "DDNSR53_ROUTE53_RECORDSSET_1_TTL=600"
    restart: always

### ddns-route53 version

v2.11.0

### Docker info

```text
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  compose: Docker Compose (Docker Inc.)
    Version:  v2.17.3
    Path:     /usr/local/lib/docker/cli-plugins/docker-compose

Server:
 Containers: 4
  Running: 4
  Paused: 0
  Stopped: 0
 Images: 4
 Server Version: 23.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
 Kernel Version: 5.13.0.x
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.544GiB
 Name: cerberus
 ID: 5bc02020-8a7e-4a5d-8160-f0e7200c3b88
 Docker Root Dir: /volume1/.@plugins/AppCentral/docker-ce/docker_lib
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

### Docker Compose config

```yaml
no configuration file provided: not found
```

### Logs

```text
Tue, 16 Jan 2024 20:54:57 UTC INF Starting ddns-route53 version=v2.11.0
Tue, 16 Jan 2024 20:54:57 UTC DBG No configuration file found
Tue, 16 Jan 2024 20:54:57 UTC INF Configuration loaded from 9 environment variables
Tue, 16 Jan 2024 20:54:57 UTC DBG {
  "credentials": {
    "accessKeyID": "censored",
    "secretAccessKey": "censored"
  },
  "route53": {
    "hostedZoneID": "censored",
    "recordsSet": [
      {
        "name": "censored",
        "type": "A",
        "ttl": 600
      },
      {
        "name": "censored",
        "type": "A",
        "ttl": 600
      }
    ]
  }
}
Tue, 16 Jan 2024 20:54:57 UTC INF Current WAN IPv4: censored
Tue, 16 Jan 2024 20:54:58 UTC INF WAN IPv4 has not changed for censored. record set
Tue, 16 Jan 2024 20:54:58 UTC INF WAN IPv4 has not changed for censored. record set
Tue, 16 Jan 2024 20:54:58 UTC WRN No Route53 record set to update. Skipping...
Tue, 16 Jan 2024 20:54:58 UTC INF Cron initialized with schedule */30 * * * *
Tue, 16 Jan 2024 20:54:58 UTC INF Next run in 5 minutes 1 second (2024-01-16 21:00:00 +0000 UTC)
```

### Additional info

Other containers on the same system (MariaDB, Pi-hole) do not exhibit this issue and respect the TZ value set in docker compose during their operation.

**Comment by crazy-max** [comment]
TZ needs to be set in the `SCHEDULE` env as well, see https://crazymax.dev/ddns-route53/faq/#timezone
