### ISSUE TITLE
How can I now the requset

### ISSUE THREAD

**Issue by Alpha-Zark** [crazy-max/ddns-route53#1208]
### Description

We all know that DDNS actually retrieves the WAN IP address of the local machine by requesting external resources. I want to know which URL this DDNS program is requesting to get the IP address—because I have set up proxy internet access, it always retrieves the proxy address. I need to ignore this URL in the proxy rules to get the correct WAN IP

**Comment by szhu25** [comment]
Seems like the following are the sites used to check your IP addresses

IPv4: https://github.com/crazy-max/ddns-route53/blob/master/pkg/wanip/client.go#L74-L77
IPv6: https://github.com/crazy-max/ddns-route53/blob/master/pkg/wanip/client.go#L102-L105

**Comment by crazy-max** [comment]
https://crazymax.dev/ddns-route53/faq/#where-is-my-public-ip-address-sourced-from
