### ISSUE TITLE
Support AWS Environment Variables in Route53 Session Creations

### ISSUE THREAD

**Issue by stephbu** [crazy-max/ddns-route53#130]
It'd be pretty handy to support passing AWS security context through environment variables in addition configuration section - specifically this would enable storing and pass credentials using mechanisms such as Kubernetes secrets.

AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY

Specifically the *Configuration.Check method demands credentials get loaded from the file.  Seems like the shortest path is to look for the environment variables if the credential block is not fully populated.  I'll take a look later and maybe come back with a PR.

**Comment by crazy-max** [comment]
@stephbu `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY` and `AWS_HOSTED_ZONE_ID` environment variables are now available. See https://github.com/crazy-max/ddns-route53/blob/master/doc/configuration.md for more info.
