### ISSUE TITLE
[Feature] Run once on startup

### ISSUE THREAD

**Issue by leosunmo** [crazy-max/ddns-route53#2]
Loving this project, thank you so much!

Somewhat unimportant feature request but would it be possible to execute a once-off DNS sync on start-up? Would be nice for testing purposes and being sure that it actually works so you don't have to come back in 30min or more.

**Comment by crazy-max** [comment]
Hi @leosunmo, simply remove flag `--schedule` and it will be run once!

**Comment by leosunmo** [comment]
But I still want it to run on a schedule, just provide an option to execute right away before counting down to the next occurrence.

**Comment by crazy-max** [comment]
Oh ok "righ away" gotcha ;)

**Comment by crazy-max** [comment]
Should be ok with latest release, let me know.
