### ISSUE TITLE
Systemd service

### ISSUE THREAD

**Issue by tomdeblende** [crazy-max/ddns-route53#3]
What would be the preferred way to run this in the background, and have it restarted upon system reboots?

**Comment by crazy-max** [comment]
Depends on your system but you can use the docker image as [explained in the README](https://github.com/crazy-max/ddns-route53#docker).

**Comment by tomdeblende** [comment]
Yeah, I saw the docker image, but I'd rather avoid the overhead. It would
make more sense to be able to run this deamonized or better even as a
service.

**Comment by crazy-max** [comment]
What's your host platform/arch ?

**Comment by tomdeblende** [comment]
I'm running it in an Open Media Vault distro, based on Debian 9.9.

**Comment by crazy-max** [comment]
Ok I will provide a ddns-route53 service sample for systemd.

**Comment by crazy-max** [comment]
@tomdeblende I have added instruction to [create a Linux service](https://github.com/crazy-max/ddns-route53/blob/master/doc/install/linux-service.md). Let me know.
