### ISSUE TITLE
Error getting IPv6 address when running in Docker

### ISSUE THREAD

**Issue by lesteenman** [crazy-max/ddns-route53#38]
When I run ddns-route53 on Docker, I'm getting the following error:

`Cannot get WAN IPv6 address error="Get https://v6.ident.me/: dial tcp [2a01:7e00::f03c:91ff:fe70:2b9d]:443: connect: cannot assign requested address"`

When I run it from the binary on the same machine, it successfully updates my AAAA record.

**Comment by lesteenman** [comment]
I believe the issue is simply that I have not set up my Docker containers and networks to use IPv6. I'll look into it.

**Comment by crazy-max** [comment]
@lesteenman Yes that's it, IPv6 is disabled by default on Docker daemon.

If IPv6 is enabled you should have something like this using the following command:

```
$ docker run -it alpine ash -c "ip -6 addr show dev eth0; ip -6 route show"
15: eth0: <BROADCAST,UP,LOWER_UP> mtu 1500
   inet6 2001:db8:1:0:0:242:ac11:3/64 scope global
      valid_lft forever preferred_lft forever
   inet6 fe80::42:acff:fe11:3/64 scope link
      valid_lft forever preferred_lft forever

2001:db8:1::/64 dev eth0  proto kernel  metric 256
fe80::/64 dev eth0  proto kernel  metric 256
default via fe80::1 dev eth0  metric 1024
```

More info: https://docs.docker.com/config/daemon/ipv6/
