### ISSUE TITLE
annot update records set error="SignatureDoesNotMatch:

### ISSUE THREAD

**Issue by azayu** [crazy-max/ddns-route53#40]
ERR Cannot update records set error="SignatureDoesNotMatch: Signature expired: 20191218T101837Z is 
now earlier than 20191218T102749Z (20191218T103249Z - 5 min.)\n\tstatus code: 403, request id: b326bb3d-70b0-45c0-a24f-ec712ba8bf
a6"

**Comment by crazy-max** [comment]
@azayu Please create a proper [bug report](https://github.com/crazy-max/ddns-route53/issues/new?template=bug_report.md).
