### ISSUE TITLE
Automatically detect timezone by mounting /etc/localtime in docker

### ISSUE THREAD

**Issue by noeRls** [crazy-max/ddns-route53#42]
Hi, i have a suggestion,

It's a known practice to mount /etc/localtime in read only to deduce the timezone.

**Comment by crazy-max** [comment]
@noeRls 

> It's a known practice to mount /etc/localtime in read only to deduce the timezone.

Maybe for you but try this with a Windows container. It also fails on some distribs and OSX (#2396). Also, if `tzdata` package is installed in your Docker image, it takes care of timezone through [`TZ` environment variable](https://data.iana.org/time-zones/tz-link.html). I think this is the most elegant way to set timezone.

For ddns-route53, the timezone is managed directly at the application level through the environment variable `TZ`, so I wonder what's your point here?
