### ISSUE TITLE
Configuration Passed in by Environment Variables doesn't Seem to be Validated

### ISSUE THREAD

**Issue by stellarpower** [crazy-max/ddns-route53#539]
### Behaviour
- I am using this image as part of an Ansible deployment, and a typo in my playbook resulted in an extra curly brace being inserted into the domain name (because the configs are templated from variables - the result was e.g. `subdomain.example.com}.`)
- I am passing in configuration via environment variables in the podman args, as in [the docs here](https://crazymax.dev/ddns-route53/config/#environment-variables)
- This means that I had a route53 container up for about two weeks with an invalid configuratioin, and a domain it wasn't ever going to be able to change. Because my IP remained stable for a good long time, it continued happily, and it was only when I had an outage today I was assigned a new IP and errors revealed themselves.

#### Steps to reproduce this issue

1. Recreate the example from the docs for configuration via environment variables
2. Change `DDNSR53_ROUTE53_RECORDSSET_0_NAME` from `ddns.example.com.` to an (I believe) illegal domain  `ddns.example.com}.` - or try any other symbol that obviously should be erroneous for any sane setup.

#### Expected behaviour

- If possible, on startup, it'd be ideal to verify that the domain specified can be updated, without actually updating it - this way any issues that would occur dewn the line would be pre-emptively found before an update is needed.
- Alternatively, perform validation of domains (and other configs, I don't know if you do this alrerady) passed in to ensure they are legal as the minimum.

#### Actual behaviour

- It was only on trying to update the IP address with AWS that what would (as far as I know) be an invalid domain name was identified

### Configuration

* ddns-route53 version : c6652645eff7 from Docker Hub
* Platform (windows/linux) : Podman, rootless, Focal host
* System info (type `uname -a`) : N/A for container

### Logs

Afraid I lost these as I had to get this machine restarted ASAP, so the container had to be pulled down and I cleared my terminal. It should be simple enough to recreate however, simply enter an extra symbol into the domain name, before the final dot. I remember that this came out as an escape sequecne. I presume it'll be straightforward, but if there are nay issues recreating I can get back to you.

Thanks for providing this!!

**Comment by crazy-max** [comment]
Makes sense, thanks for your report!

**Comment by crazy-max** [comment]
Should be good with latest aws sdk https://github.com/crazy-max/ddns-route53/pull/899
