### ISSUE TITLE
Using CONFIG environment variable doesn't work in Docker

### ISSUE THREAD

**Issue by kamilon** [crazy-max/ddns-route53#542]
#### Steps to reproduce this issue

1. Create a docker container with config pointed to a file
2. Run docker container
3. Fail

#### Expected behaviour

> File should be loaded based on CONFIG environment variable path

#### Actual behaviour

> Dockerfile --config argument path is used instead

### Logs

```
Tue, 21 Sep 2021 21:04:51 PDT INF Starting ddns-route53 version=2.7.0
Tue, 21 Sep 2021 21:04:51 PDT DBG No configuration file found
Tue, 21 Sep 2021 21:04:51 PDT DBG No DDNSR53_* environment variables defined
Tue, 21 Sep 2021 21:04:51 PDT FTL Cannot load configuration error="route53 configuration required"
```

I was able to get this running by overridding the CMD when calling the docker container to use the value that was in my CONFIG environment variable, but I'd rather not have to do that as it feels hacky.

**Comment by crazy-max** [comment]
@kamilon 

> Create a docker container with config pointed to a file

What's the `docker run` cmd or compose file you're using?
