### ISSUE TITLE
Getting a 403 error

### ISSUE THREAD

**Issue by miguelarios** [crazy-max/ddns-route53#550]
I tried searching already the past issues and can't find any solution. I changed my `accessKeyID` and `secretAccessKey` and restarted the docker image and no cigar. Not sure what else to try?

`The security token included in the request is invalid.`

**Comment by crazy-max** [comment]
@miguelarios 

> `The security token included in the request is invalid.`

This error is returned by AWS when trying to perform the update. Check your [User and IAM policies](https://crazymax.dev/ddns-route53/usage/prerequisites/). Are you using an MFA device?

**Comment by miguelarios** [comment]
> @miguelarios 
> 
> 
> 
> > `The security token included in the request is invalid.`
> 
> 
> 
> This error is returned by AWS when trying to perform the update. Check your [User and IAM policies](https://crazymax.dev/ddns-route53/usage/prerequisites/). Are you using an MFA device?

So actually what fixed it was that my container has example value for the environment variables. When I erased those then it took my config file which is what it was using all along but I think maybe an update that I made caused the container to prefer environment variables and if none present it searches for a config file. 

Thanks you!
