### ISSUE TITLE
[Feature] AWS Cloudfront CDN to hide origin IP

### ISSUE THREAD

**Issue by shawnngtq** [crazy-max/ddns-route53#617]
Hi @crazy-max , thanks for this awesome library and documentation, works flawlessly. 😁 

Wonder if we can mask/hide origin IP in route53? By adding AWS Cloudfront as optional config?

Inspired from Cloudflare. It offers a nice security feature which hides the origin IP and returns a proxy one when a DNS lookup is performed against the domain. This is helpful in preventing direct attacks to the domain's origin IP.

**Comment by crazy-max** [comment]
@shawnngtq 

> Wonder if we can mask/hide origin IP in route53? By adding AWS Cloudfront as optional config?

Yes I think you can create a distribution in AWS Cloudfront with your origin domain name which has a private hosted zone on Route53 which will be used by ddns-route53 to update its record (eg. `mydomain.net`). Then you need another public hosted zone (eg. `mydomain.com`) that will have a CNAME record pointing to the CloudFront distribution (eg. `d111111abcdef8.cloudfront.net`). See this blog post for more details: https://support.productboard.com/hc/en-us/articles/360060271434-Customize-your-Portal-s-domain-with-CloudFront-and-Route53.

No need to add anything in ddns-route53 as it's not its purpose.
