### ISSUE TITLE
Error adding network: failed to create bridge "cni0": could not add "cni0": operation not supported

### ISSUE THREAD

**Issue by thanneman79** [crazy-max/ddns-route53#624]
### Behaviour

Error starting of container.

#### Steps to reproduce this issue

1. Updated to /mnt/data/on_boot.d/20-ddns-route53.sh to latest script from install instructions.
2. Removed ddns-route53 image
3. Executed sc

#### Expected behaviour

 container starts and updates dns entry with route 53

#### Actual behaviour
# /mnt/data/on_boot.d/20-ddns-route53.sh
Trying to pull docker.io/crazymax/ddns-route53:latest...
Getting image source signatures
Copying blob 552d1f2373af done
Copying blob b52c5e34a143 done
Copying blob 09f832a68278 done
Copying config 2c90573f47 done
Writing manifest to image destination
Storing signatures
ERRO[0003] Error adding network: failed to create bridge "cni0": could not add "cni0": operation not supported
ERRO[0003] Error while adding pod to CNI network "podman": failed to create bridge "cni0": could not add "cni0": operation not supported
Error: error configuring network namespace for container c1d9b8f10d2d4fe3a9962d79708376fd57056d65d8210021c06b650fe6b3acc7: failed to create bridge "cni0": could not add "cni0": operation not supported

### Configuration

* ddns-route53 version : 
* Platform (windows/linux) :
* System info (type `uname -a`) : 

```yml
# paste your YAML configuration file here and remove sensitive data
```
credentials:
  accessKeyID: "KEY REDACTED"
  secretAccessKey: "REDACTED"

route53:
  hostedZoneID: "HOSTZONE REDACTED"
  recordsSet:
    - name: "NAME REDACTED"
      type: "A"
      ttl: 300
    - name: "NAME REDACTED"
      type: "AAAA"
      ttl: 300

### Logs

```
# paste logs here (set log level to debug first)
```
Empty

**Comment by crazy-max** [comment]
> Updated to /mnt/data/on_boot.d/20-ddns-route53.sh to latest script from install instructions.

What script?

> ```
> ERRO[0003] Error adding network: failed to create bridge "cni0": could not add "cni0": operation not supported
> ERRO[0003] Error while adding pod to CNI network "podman": failed to create bridge "cni0": could not add "cni0": operation not supported
> Error: error configuring network namespace for container c1d9b8f10d2d4fe3a9962d79708376fd57056d65d8210021c06b650fe6b3acc7: failed to create bridge "cni0": could not add "cni0": operation not supported
> ```

Looks like an issue with Podman, not sure it's related to ddns-route53.

**Comment by thanneman79** [comment]
The script I refrenced is the shell sciprt /mnt/data/on_boot.d/20-ddns-route53.sh script from the  UniFi OS device install section of the ddns-route53 main page.

Starting try to dig in, a lot is not stuff I know so I'm learning as I go through it. 

The library the shell script tries to pull "https://github.com/containernetworking/plugins/releases/download/v0.8.6/cni-plugins-linux-arm64-v0.8.6"  no longer exists. Looks like they may have change structure of the the repository and have new versions. I'm trying to figure out the new location. 

I think this is the right direction as the error refers to setting up network stuff for the ddns-route53 container related to the above library.

**Comment by crazy-max** [comment]
cc @amdprophet

**Comment by thanneman79** [comment]
Disregard copy and paste didn't grab the extension that wrapped to a newline. The file is still at the location so I'm back to square one.

**Comment by thanneman79** [comment]
Found the issue and resolution. 

https://github.com/boostchicken-dev/udm-utilities/issues/212

Short of it, the interface cni0 no longer exists after upgrading to to UDM Pro 1.10.0 (Thread doesn't indicate if UDM also). 

Re-creating the interface "ip link add cni0 type bridge" corrects the issue.
