### ISSUE TITLE
ttl not updated if ip does not change

### ISSUE THREAD

**Issue by benedikt-bartscher** [crazy-max/ddns-route53#912]
#### Steps to reproduce this issue

1. change your TTL config
2. restart ddns-route53

#### Expected behaviour

The DNS records TTL gets adjusted.

#### Actual behaviour

ddns-route53 reports that our WAN ip did not change and does nothing

**Comment by crazy-max** [comment]
@benedikt-bartscher Record will only be updated if IP has changed. Not sure if we should update the record if TTL has changed though.
