### ISSUE TITLE
Trouble setting SCHEDULE via k3s/TrueCharts

### ISSUE THREAD

**Issue by kyeotic** [crazy-max/ddns-route53#940]
First, thank you for making this. It works great and is exactly what I needed after finding Route53 support missing from ddns-updater.

I do have [an issue ](https://www.truenas.com/community/threads/docker-unable-to-provide-environment-variables-einval.108324/) trying to run this in a docker container that's being configured by k3s/TrueCharts. The `SCHEDULE` value doesn't sanitize well and can't be provided. I can provide configuration via the yaml file, but it doesn't appear that `SCHEDULE` is supported this way.

It would be awesome if it could be configured from the yaml route.

**Comment by crazy-max** [comment]
> The `SCHEDULE` value doesn't sanitize well and can't be provided

Well that seems to be a TrueNAS issue that should be fixed on their side.

> I can provide configuration via the yaml file, but it doesn't appear that `SCHEDULE` is supported this way.
>
> It would be awesome if it could be configured from the yaml route.

This is not an option. SCHEDULE value like log level and other global opts are handled before the config file is parsed.

What you can do is using the `--schedule` flag I think looking at the TrueNAS docs: https://www.truenas.com/docs/scale/scaletutorials/apps/docker/

![image](https://github.com/crazy-max/ddns-route53/assets/1951866/362ef8d1-520f-446f-8686-ca7a406291e0)

And add "Container Args":

```
--config="/ddns-route53.yml"
```

```
--schedule="*/30 * * * *"
```

Not sure why they bother to have multiple commands and args. The UX looks pretty bad tbh.
